<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tmstgift_model extends CI_Model
{

    public $table = 'tmstgift';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,namagift,point,harga,productimage,status');
        $this->datatables->from('tmstgift');
        //add this line for join
        //$this->datatables->join('table2', 'tmstgift.field = table2.field');
        if($this->session->userdata('role')!='Staff'){ 
            $this->datatables->add_column('action', anchor(site_url('tmstgift/read/$1'),'Read')." | ".anchor(site_url('tmstgift/update/$1'),'Update')." | ".anchor(site_url('tmstgift/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        }
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('namagift', $q);
	$this->db->or_like('point', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('productimage', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('namagift', $q);
	$this->db->or_like('point', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('productimage', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getaktifgift(){
        $this->db->where('status', 1);
        return $this->db->get($this->table)->result();
    }
}

/* End of file Tmstgift_model.php */
/* Location: ./application/models/Tmstgift_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-02-15 03:50:43 */
/* http://harviacode.com */