<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Toutletpoint_model extends CI_Model
{

    public $table = 'toutletpoint';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        
//$monthName = date('F', mktime(0, 0, 0, $monthNum, 10)); // March
        $this->datatables->select('toutletpoint.id,tmstoutlet.outlet,toutletpoint.totalpoint,MONTHNAME(concat("2011-",bulan,"-01")) as bulan ,tahun,aktif,usedpoint,sisapoint');
        $this->datatables->from('toutletpoint');
        //add this line for join
        $this->datatables->join('tmstoutlet', 'toutletpoint.outlet = tmstoutlet.id');
        $this->datatables->add_column('action', anchor(site_url('toutletpoint/read/$1'),'Read')." | ".anchor(site_url('toutletpoint/update/$1'),'Update')." | ".anchor(site_url('toutletpoint/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('outlet', $q);
	$this->db->or_like('totalpoint', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('aktif', $q);
	$this->db->or_like('usedpoint', $q);
	$this->db->or_like('sisapoint', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('outlet', $q);
	$this->db->or_like('totalpoint', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('aktif', $q);
	$this->db->or_like('usedpoint', $q);
	$this->db->or_like('sisapoint', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Toutletpoint_model.php */
/* Location: ./application/models/Toutletpoint_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-24 05:32:18 */
/* http://harviacode.com */